                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #include<iostream>
																																																																																																																																																																																		      using namespace std;
																																																																																																																																																																																			  int main(){
																																																																																																																																																																																			  double tax,tip,totalbill,meal_cost=88.67;
																																																																																																																																																																																			     tax=meal_cost*0.0675;
																																																																																																																																																																																			     tip=(meal_cost + tax)*0.2;
																																																																																																																																																																																			     totalbill=meal_cost+tax+tip;
																																																																																																																																																																																			     cout<<"meal cost: $"<<meal_cost<<endl;
																																																																																																																																																																																			     cout<<"tax: $"<<tax<<endl;
																																																																																																																																																																																			     cout<<"tip: $"<<tip<<endl;
																																																																																																																																																																																			     cout<<"total bill: $"<<totalbill;
																																																																																																																																																																																			  return 0;   
																																																																																																																																																																																			  	
																																																																																																																																																																																			  }                                        
